### ISSUE TITLE
Set Airspeed Mode crashes to Desktop

### ISSUE THREAD

**Issue by makerplane-jnicol** [makerplane/pyEfis#105]
Set Airspeed Mode in the menu system toggles between TAS, IAS and GS.  The menu uses the following to achieve this with touch buttons:
          -['Mode', 'Set Airspeed Mode', ' ']

When pyEfis is loaded for the first time, select the menu item called Mode and the system will crash to desktop.  If a user selects a different screen first and then Mode, it will not crash.

**Comment by birkelbach** [comment]
I can't duplicate the crash but I do get an exception.  I'll try to fix the exception but I have my doubts about the usefulness of this feature.  It's built into the airspeed indicator object and I think it's a really bad idea to change the kind of airspeed we display on what should be expected to be an IAS indicator.
