### ISSUE TITLE
proper handling of units for BARO display

### ISSUE THREAD

**Issue by qubolino** [makerplane/pyEfis#108]
i'd like to have BARO displayed in hPa but i don't want to change the db field unit nor add a new one since that would be redundant. 
what is the proper way to handle different units in pyEfis pls. ideally i'd like to comply to what's already beeen done

**Comment by birkelbach** [comment]
We have alternate units functionality in some of the engine instruments.  The way that it's done there IIRC is there is an alternate unit formula and they react to a signal to change back and forth.
