### ISSUE TITLE
Configuration System

### ISSUE THREAD

**Issue by birkelbach** [makerplane/pyEfis#2]
A configuration system needs to be built so that the end users will be able to build their own screens without having to do any programming.  Whether it's just a text based configuration or a graphical one or both.

**Comment by birkelbach** [comment]
What I've come up with on this is a half solution.  The screens are still programmed in Python/PyQt but they are separate modules and really all that has to be done is copy an existing screen and change things like database key string, sizes, positions etc.  Most of the real work happens in the individual instrument modules.  Configuration of screens is going to be a big project.

**Comment by e100** [comment]
The new screenbuilder resolves this so closing.

https://github.com/makerplane/pyEfis/blob/master/docs/screenbuilder.md
