### ISSUE TITLE
YAML Configuration

### ISSUE THREAD

**Issue by birkelbach** [makerplane/pyEfis#43]
What do you guys think about changing the main configuration file to YAML?  It's what I did with FIX-Gateway and I like it much better.  It would also make it consistent with that program.  It's also much more powerful.

**Comment by neil-d95** [comment]
It's on the list it'll prob not drop till after OSH.

  On January 28, 2019 at 12:20 PM Phil Birkelbach <notifications@github.com> wrote:
 
 
 What do you guys think about changing the main configuration file to YAML? It's what I did with FIX-Gateway and I like it much better. It would also make it consistent with that program. It's also much more powerful.

**Comment by birkelbach** [comment]
Don't hate me but I kept running into situations where a YAML configuration file would make life much easier so I did it.  It wasn't that difficult.  I don't think it will affect what you guys are working on.  If you think it will, let me know and I'll pull your branches and see if I can work it out.
