### ISSUE TITLE
Implement Engine only Screen

### ISSUE THREAD

**Issue by neil-d95** [makerplane/pyEfis#46]
Implement Engine only screen

**Comment by birkelbach** [comment]
I have an ems branch on my repo at...
[ems](https://github.com/birkelbach/pyEfis/tree/ems)
If you guys want to check out the progress.  You'll have to run it with the --config-file config/ems.cfg argument.

**Comment by birkelbach** [comment]
![pyEfis py_007](https://user-images.githubusercontent.com/474187/54290319-be250500-4578-11e9-90f1-28b20f0118a7.png)

It could still use some tweaks but it's useful now.

**Comment by Maker42** [comment]
I was really looking forward to this pull request! Looks awesome Phil!

**Comment by makerplane-jnicol** [comment]
Looks good!  Do you also have the ability to change to celcius for OAT and other temps for non-savages?On Mar 13, 2019 4:24 PM, Phil Birkelbach <notifications@github.com> wrote:
It could still use some tweaks but it's useful now.
