### ISSUE TITLE
Compact ganged gauges

### ISSUE THREAD

**Issue by Maker42** [makerplane/pyEfis#54]
We should have a more compact way to display a group of gauges, such as all fuel tanks, oil pressure & temperature, CHT + EGT/TIT, or CHT for all cylinders.

**Comment by birkelbach** [comment]
I'm actually working on that right now.  Trying to build an EGT display that has normalization, peak detection and all those goodies in it.

**Comment by Maker42** [comment]
Great minds think alike I see. :)

**Comment by e100** [comment]
This is implemented in the screenbuilder, documentation:
https://github.com/makerplane/pyEfis/blob/master/docs/screenbuilder.md#ganged-instruments
