### ISSUE TITLE
Round Instruments Need Some Love

### ISSUE THREAD

**Issue by birkelbach** [makerplane/pyEfis#8]
I'm not even sure whether most people will even want the round "six-pack" style instruments, but they are a bit on the weak side (I can say that because I wrote most of them) so if anybody shows any interest in using them we'll get them fixed up.  The flight sim guys are probably the ones that would want them.  I doubt many people will install pyEfis in an actual airplane on an LCD screen and then put pictures of steam gauges on it, but I've been wrong before.

**Comment by makerplane-jnicol** [comment]
Yeah, I am pretty sure you are right, but we both could be wrong..... I might reach out to the Flight Sim community to see if someone wants to contribute to that, but also perhaps get stuck in to more digital instruments and skin alternatives.
