### ISSUE TITLE
Adding EGT warn and alarm limits to ini file creates errors at runtime

### ISSUE THREAD

**Issue by j-omega** [makerplane/pyEfis#95]

**Comment by birkelbach** [comment]
I believe that this is a FIXGateway Issue and not a PyEfis issue correct?  Is it the low limits that are causing the problems or the high limits?

**Comment by j-omega** [comment]
I would need to get it all setup again to answer that. It should be very simple to reproduce. I believe it was both high and low.

**Comment by birkelbach** [comment]
This is a FIXGateway issue.  Basically you have to add lowWarn and lowAlarm to the database.yaml file if you want those auxiliary values to exist.  Once I added those it worked fine.

**Comment by j-omega** [comment]
Understood. Would you please update the default YAML to include those?

**Comment by j-omega** [comment]
Understood. Would you please update the default YAML to include those?
